services:
  database:
    image: mariadb:10.11
    container_name: mariadb_container
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: app_sc
      MARIADB_USER: app_user
      MARIADB_PASSWORD: app_password
    ports:
      - "3311:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data: